--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VsrStudio/VLobbyCore
build-by-default: true
branches:
- main
projects:
  VLobbyCore:
    path: ""
    libs:
      - src: MyFreds/libEco/libEco
        version: ^4.0.0
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: Ifera/ScoreFactory/ScoreFactory
        version: ^3.1.0
      - src: jasonw4331/libpmquery/libpmquery
        version: ^1.0.0
...
