--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VsrStudio/VLobbyCore
build-by-default: true
branches:
- main
projects:
  VLobbyCore:
    path: ""
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^3.0.0
        branch: stable
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
