name: VLobbyCore
main: VsrStudio\VLC\LobbyCore
version: 1.0.0
api: 5.0.0
author: VsrStudio
website: vststudio.web.id
softdepend: Parties, SimpleClorhes

commands:
  vchat:
    description: "Send VIP chat messages"
    usage: "/vchat <message>"
    aliases: ["vc"]
    permission: vipchat.command

permissions:
  vipchat.command:
    description: "Using VIP Chat"
    default: op
