name: VLobbyCore
main: VsrStudio\VLC\LobbyCore
version: 2.0.0
api: 5.0.0
author: VsrStudio
website: vststudio.web.id
softdepend: [Parties, SimpleClothes]

permissions:
  vipchat.command:
    description: "Using VIP Chat"
    default: op
  protection.command:
    description: "protection on off"
    default: op
