#Venity Network LobbyCore By VsrStudio Lothlus Network

# Button1: -> Name Button No "§"
#    type: "server" -> Type Server
#    ip: "example.com"
#    port: 19132 -> Show Players in server

# Button2: -> Name Button No "§"
#    type: "world" -> Type World
#    command: "warp lobby"
#    worlds: ["Survival"] -> Show Players in world

# type: "world" / "server"
# worlds: ["Lobby", "Survival"] -> Show TotalPlayers in world

games:
  survival:
    type: "world"
    command: "warp Survival"
    worlds: ["Survival"]
  vivasmp:
    type: "world"
    command: "warp VivaSmp"
    worlds: ["vsrstudio", "baikbanget"]
  squidgame:
    type: "server"
    ip: "example.com"
    port: 19132
  duels:
    type: "world"
    command: "duels random"
    worlds: ["duel1", "duel2", "duel3"]
  bedwars:
    type: "server"
    ip: "bedwars.example.com"
    port: 19132
  skywars:
    type: "world"
    command: "skywars select"
    worlds: ["skywarsmap"]


Join-Message: "§8[§b+§8]§b{player}"

Quit-Message: "§8[§c-§8]§c{player}"

#Permissions Message Confjg

NotPermissions: "§cYou do not have permissions to use"
