#Venity Network LobbyCore By VsrStudio Lothlus Network

# Button1: -> Name Button No "§"
#    type: "server" -> Type Server
#    ip: "example.com"
#    port: 19132 -> Show Players in server

# Button2: -> Name Button No "§"
#    type: "world" -> Type World
#    command: "warp lobby"
#    worlds: ["Survival"] -> Show Players in world

# type: "world" / "server"
# worlds: ["Lobby", "Survival"] -> Show TotalPlayers in world

games:
  bedwars:
    type: "server"
    ip: "bedwars.example.com"
    port: 19132
  skywars:
    type: "world"
    command: "skywars select"
    worlds: ["skywarsmap"]


Join-Message: "§8[§b+§8]§b{player}"

Quit-Message: "§8[§c-§8]§c{player}"

#Permissions Message Confjg
NotPermissions: "§cYou do not have permissions to use"

server-name: "Lobby-1"

scoreboard:
  enabled: true           # set false => scoreboard does not appear at all
  update-interval-ticks: 40   # how often to refresh (2 seconds = 40 ticks)
  title: "§l§bLobby"
  lines:
    - "§7---------------------"
    - "§ePlayer: §f{player}"
    - "§eRank: §f{rank}"
    - "§eOnline: §f{online}"
    - "§ePing: §f{ping} ms"
    - "§eTPS: §f{tps}"
    - "§eItem: §f{item-id}"
    - "§eJump: §f{jump}"
    - "§ePos: §f{x}, {y}, {z}"
    - "§eServer: §f{server-name}"
    - "§7---------------------"

# Items Settings
items:
  - item: "dye:gray"
    name: "§7Hide Player §7(Hold / Right Click)"
    slot: 0
    action: "toggle-visibility"

  - item: "compass"
    name: "§aServer Selector §7(Hold / Right Click)"
    slot: 1
    action: "open-ui"
    ui: "server-selector"

  - item: "popped_chorus_fruit"
    name: "§dSocial §7(Hold / Right Click)"
    slot: 2
    action: "open-ui"
    ui: "social"

  - item: "player_head"
    name: "§eProfile §7(Hold / Right Click)"
    slot: 3
    action: "open-ui"
    ui: "profile"

  - item: "poppy"
    name: "§cCosmetic §7(Hold / Right Click)"
    slot: 4
    action: "command"
    command: "sc"
